version: '3.7'

services:
  auth:
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./services/auth/Auth.Web/postgres.env
    depends_on:
      - auth-db
    build:
      context: ./services/auth/Auth.Web
      dockerfile: ./Dockerfile      
    ports:
      - "5000:5000"
  
  auth-db:
    image: postgres:14    
    env_file:
      - ./services/auth/Auth.Web/postgres.env
    volumes:
      - auth-db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
      
volumes:
  auth-db:
